# Generated by Django 5.0.2 on 2024-03-24 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_commentactivity_commenthotel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answered', models.BooleanField(default=False)),
                ('custom_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='packages.custompackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
