# Generated by Django 5.0.2 on 2024-03-24 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='custom_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='packages.premadepackage'),
        ),
    ]
