# Generated by Django 5.0.2 on 2024-03-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_alter_question_custom_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='custom_package',
            new_name='pre_made_package',
        ),
    ]
