# Generated by Django 5.0.2 on 2024-03-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_rename_custom_package_question_pre_made_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.TextField(default=''),
        ),
    ]
