# Generated by Django 5.0.2 on 2024-03-27 23:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0006_custompackage_agency"),
        ("packages", "0012_question_created_at_alter_question_answer_text"),
    ]

    operations = []
