# Generated by Django 5.0.2 on 2024-04-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0015_activity_agency_hotel_agency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="city",
            field=models.CharField(max_length=100),
        ),
    ]
