# Generated by Django 5.0.2 on 2024-03-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_booking_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="paid",
        ),
        migrations.AddField(
            model_name="booking",
            name="reserved_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("none", "None"), ("reserved", "Reserved"), ("paid", "Paid")],
                default="none",
                max_length=10,
            ),
        ),
    ]
