# Generated by Django 5.0.2 on 2024-03-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_remove_booking_paid_booking_reserved_until_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="tracking_id",
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
    ]
