# Generated by Django 5.0.2 on 2024-04-03 00:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_booking_tracking_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
