# Generated by Django 5.0.2 on 2024-04-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_booking_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
